#!/usr/bin/env bash
#
# scripts/ops/vercel-prod-env.sh
#
# Idempotent batch-add of all Vercel Production env vars, grouped
# by category. Re-running the script skips env vars already present
# in the Production scope (`vercel env ls production` parse), so it
# is safe to invoke multiple times.
#
# Usage:
#   # 0. Run from the project root (where vercel.json lives).
#
#   1. Authenticate with Vercel (one-time per shell):
#        vercel login
#
#   2. Set the env values as local shell vars (so the script can pipe
#      them into `vercel env add` without prompting). The script maps
#      each Vercel env var to a LOCAL_SHELL_VAR — see the category
#      table below for the exact mapping. Example:
#        export SUPABASE_DATABASE_URL='postgres://postgres.<REF>:<PWD>@aws-0-<region>.pooler.supabase.com:6543/postgres'
#        export SUPABASE_DIRECT_URL='postgres://postgres:<PWD>@db.<REF>.supabase.com:5432/postgres'
#        export SUPABASE_URL='https://<REF>.supabase.co'
#        export SUPABASE_SERVICE_ROLE_KEY='<service-role-jwt>'
#        export SUPABASE_ANON_KEY='<anon-jwt>'
#        export APP_URL='https://www.courssy.com'
#        export LEMONSQUEEZY_API_KEY='sk_live_...'
#        export LEMONSQUEEZY_STORE_ID='<store-id>'
#        export LEMONSQUEEZY_WEBHOOK_SECRET='<webhook-secret>'
#        export EMAIL_SERVER_HOST='smtp.gmail.com'
#        export EMAIL_SERVER_PORT='587'
#        export EMAIL_SERVER_USER='noreply@courssy.com'
#        export EMAIL_SERVER_PASSWORD='<app-password>'
#        export EMAIL_FROM='noreply@courssy.com'
#        export UPSTASH_REDIS_REST_URL='https://<instance>.upstash.io'
#        export UPSTASH_REDIS_REST_TOKEN='<token>'
#        export ALERT_WEBHOOK_URL='https://hooks.slack.com/services/...'
#        # CRON_SECRET is auto-generated by --auto-generate if unset
#
#   3. Run the script:
#        bash scripts/ops/vercel-prod-env.sh
#
#      Or, preview what WOULD be added (no `vercel env add` calls):
#        bash scripts/ops/vercel-prod-env.sh --dry-run
#
#      Or, auto-generate the missing random secrets (CRON_SECRET +
#      LOG_ERROR_SECRET) when their shell vars are unset:
#        bash scripts/ops/vercel-prod-env.sh --auto-generate
#
# Categories:
#   1. Supabase DB + Auth        (DATABASE_URL, DIRECT_URL, SUPABASE_URL,
#                                  SUPABASE_SERVICE_ROLE_KEY, optional Google
#                                  OAuth creds — typically set in Supabase
#                                  Auth dashboard instead, see comment)
#   2. Lemon Squeezy             (LEMONSQUEEZY_API_KEY, _STORE_ID, _WEBHOOK_SECRET)
#   3. Email (SMTP)              (EMAIL_SERVER_HOST/PORT/USER/PASSWORD/FROM)
#   4. Redis (Upstash)           (KV_REST_API_URL + _TOKEN — preferred names
#                                  for Vercel Marketplace installs)
#   5. ALERT_WEBHOOK_URL         (Slack/Discord alert channel)
#   6. CRON_SECRET               (cron route auth — Bearer token)
#   7. NEXT_PUBLIC_*             (browser-exposed: APP_URL, SUPABASE_URL,
#                                  SUPABASE_ANON_KEY)
#   8. Other optional            (LOG_ERROR_SECRET, OPENAI_API_KEY
#                                  — skipped if shell vars unset; no error)
#
# Cross-refs:
#   - docs/production.md §1.2 (Production env list)
#   - docs/ops/lemon-squeezy-live-setup.md §1.3 + §5.2 (LS env schema)
#   - docs/production-hardening.md §11 (Deploy-time env matrix)
#   - scripts/ops/staging-env.sh (sibling helper; sets up staging env vars
#     in the operator's current shell)
#   - src/lib/env.ts (canonical env definitions; the env schema
#     referenced by `npx tsc --noEmit` at build time)
#
# Why a script (not a runbook):
#   Vercel env vars must be set per-scope. With 25+ vars to add, the
#   manual process is error-prone (typos, wrong scope, missed vars).
#   This script makes it reproducible + idempotent: re-running skips
#   vars already set in the Production scope.
#
# Exit codes:
#   0  success (or dry-run)
#   1  vercel CLI not in PATH or not authenticated
#   2  not in a Vercel project root (no vercel.json or .vercel/ dir)
#   3  one or more `vercel env add` calls failed (re-run after fixing
#      the offending env var; the script will skip vars it already added)
#   64 usage error (unknown flag)
#
# NOT in scope (deliberately skipped; rationale below):
#   - STRIPE_SECRET_KEY + STRIPE_WEBHOOK_SECRET
#     (LEGACY provider webhook-only — Lemon Squeezy is the PRIMARY post-
#     Phase 7. Used by the legacy webhook handler for refund/dispute
#     events that pre-date the cutover; removable after C4 drain.)
#   - USE_ACCESS_GRANT_RESOLVER
#     (feature flag with hardcoded default `'false'` — flip via
#     `npx vercel env add USE_ACCESS_GRANT_RESOLVER production "true"`
#     only during the deliberate resolver rollout in docs/phase-5*)
#   - NEXT_PUBLIC_*_STRIPE_PUBLISHABLE_KEY, ENABLE_STRIPE_CHECKOUT,
#     GOOGLE_CLIENT_ID/SECRET — REMOVED from env registry (cleanup C1b/c,
#     C2)

# CRITICAL: this script must be EXECUTED, not sourced. Sourcing would
# either kill the shell (via `set -e` + missing var) or silently skip
# checks. The shebang + explicit `set -euo pipefail` make the
# executed-only contract explicit.

set -euo pipefail

# ─── Flag parsing ──────────────────────────────────────────────────

IS_DRY_RUN=false
IS_AUTO_GENERATE=false
for arg in "$@"; do
  case "$arg" in
    --dry-run)        IS_DRY_RUN=true ;;
    --auto-generate)  IS_AUTO_GENERATE=true ;;
    --help|-h)
      sed -n '2,/^set -euo pipefail/p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      printf '\n❌ Unknown flag: %s\n' "$arg" >&2
      printf '   Run with --help for usage.\n\n' >&2
      exit 64
      ;;
  esac
done

# ─── Pre-flight: vercel CLI + auth + project root ─────────────────

if ! command -v vercel >/dev/null 2>&1; then
  printf '\n❌ vercel CLI not in PATH. Install: npm i -g vercel\n\n' >&2
  exit 1
fi

# `vercel env ls` requires auth. If it fails, prompt the user to login.
if ! vercel env ls >/dev/null 2>&1; then
  printf '\n❌ vercel CLI not authenticated. Run: vercel login\n\n' >&2
  exit 1
fi

# Must run from the project root (where vercel.json or .vercel/ lives).
if [[ ! -f vercel.json && ! -d .vercel ]]; then
  printf '\n❌ Not in a Vercel project root. Run from the directory containing vercel.json.\n\n' >&2
  exit 2
fi

# ─── Fetch existing env vars (Production scope) ───────────────────

# `vercel env ls production` output format (TSV):
#   name     value       environments
#   DATABASE_URL  *****    Production, Preview, Development
# We extract just the names — sorted for both `_is_in_production` AND
# the `comm -13` diff at the end. Capture ONCE into a file rather than
# a variable + a second `mktemp` (saves one round-trip to the Vercel API
# on every run, which matters when an operator iterates during pre-flight).
EXISTING_FILE=$(mktemp)
AFTER_FILE=$(mktemp)
trap 'rm -f "$EXISTING_FILE" "$AFTER_FILE"' EXIT INT TERM
vercel env ls production 2>/dev/null | awk 'NR>1 && $1 != "" {print $1}' | sort -u > "$EXISTING_FILE"

# Helper: returns 0 (true) if env var is already set in Production scope
_is_in_production() {
  local var_name="$1"
  grep -qxF "$var_name" "$EXISTING_FILE"
}

# Helper: generate a random secret using openssl (32 bytes base64 = 44 chars)
_gen_secret() {
  openssl rand -base64 32
}

# ─── Categories ───────────────────────────────────────────────────
# Each entry: VERCEL_NAME|LOCAL_SHELL_VAR|DESCRIPTION
# LOCAL_SHELL_VAR is the operator's local env var to source the value
# from. Description is for the dry-run output + summary lines.
#
# Category counts: 8 total (7 user-specified + 1 "Other optional").

# ── 1. Supabase DB + Auth ──────────────────────────────────────────
# DATABASE_URL/DIRECT_URL → Prisma (pooled vs direct; DIRECT_URL is
# port 5432 + IPv6-only on free tier). SUPABASE_URL/SERVICE_ROLE_KEY
# → server-side admin (storage, OAuth flows).
#
# GOOGLE OAuth credentials are NOT in this Vercel env registry: configure
# Client ID + Secret in the Supabase Dashboard (Authentication → Providers
# → Google). scripts/diagnose-oauth.ts can still read process.env for
# diagnostic visibility.
CATEGORY_SUPABASE_DB_AUTH=(
  "DATABASE_URL|SUPABASE_DATABASE_URL|Supabase pooled (port 6543, pgBouncer)"
  "DIRECT_URL|SUPABASE_DIRECT_URL|Supabase direct (port 5432, IPv6-only on free tier)"
  "SUPABASE_URL|SUPABASE_URL|Supabase project URL (https://<ref>.supabase.co)"
  "SUPABASE_SERVICE_ROLE_KEY|SUPABASE_SERVICE_ROLE_KEY|Supabase service role JWT — server-only, full privilege"
)

# ── 2. Lemon Squeezy (API + Webhook + Store) ───────────────────────
# Live values required post KYC/KYB approval. The webhook secret is
# the 32-char hex LS signs each order_created/finished/refunded payload
# with — MUST differ per environment (test → staging → prod).
CATEGORY_LEMONSQUEEZY=(
  "LEMONSQUEEZY_API_KEY|LEMONSQUEEZY_API_KEY|LS live API key (post KYC/KYB approval)"
  "LEMONSQUEEZY_STORE_ID|LEMONSQUEEZY_STORE_ID|LS live store ID"
  "LEMONSQUEEZY_WEBHOOK_SECRET|LEMONSQUEEZY_WEBHOOK_SECRET|LS live webhook signing secret (32-char hex, 6-40 chars per LS)"
)

# ── 3. Email (SMTP) ────────────────────────────────────────────────
# All 5 required by src/lib/services/email.ts. None have defaults in
# src/lib/env.ts anymore (cleanup C1e) — set explicitly to your SMTP
# provider (Resend, SendGrid, Mailgun, Gmail SMTP).
CATEGORY_EMAIL_SMTP=(
  "EMAIL_SERVER_HOST|EMAIL_SERVER_HOST|SMTP host (e.g. smtp.resend.com)"
  "EMAIL_SERVER_PORT|EMAIL_SERVER_PORT|SMTP port (e.g. 587 or 2525)"
  "EMAIL_SERVER_USER|EMAIL_SERVER_USER|SMTP username (REQUIRED for actual send)"
  "EMAIL_SERVER_PASSWORD|EMAIL_SERVER_PASSWORD|SMTP password / Resend API key"
  "EMAIL_FROM|EMAIL_FROM|From address (e.g. 'Courssy <no-reply@courssy.com>')"
)

# ── 4. Redis (Upstash) ─────────────────────────────────────────────
# src/lib/redis.ts prefers KV_REST_API_* (Vercel Marketplace install)
# but accepts UPSTASH_REDIS_REST_* (direct Upstash console) — see
# src/lib/redis.ts L128-131. Production should set the KV_* names
# (auto-attached when adding Upstash via Vercel Marketplace); the
# UPSTASH_* names are listed as ALIASES for clarity but skipped if
# `KV_REST_API_URL` is present to avoid duplicate installs.
CATEGORY_REDIS=(
  "KV_REST_API_URL|UPSTASH_REDIS_REST_URL|Upstash REST URL (Vercel Marketplace canonical name)"
  "KV_REST_API_TOKEN|UPSTASH_REDIS_REST_TOKEN|Upstash REST token (Vercel Marketplace canonical name)"
)

# ── 5. ALERT_WEBHOOK_URL ───────────────────────────────────────────
# Single env var; Slack/Discord incoming webhook URL that
# src/lib/logging/server-error-sink.ts posts to for severity=P0/P1
# alerts. Also referenced by docs/ops/uptime-monitor-setup.md §5.1.
# If unset the error-sink falls back to console logging only (not
# acceptable for prod).
CATEGORY_ALERT_WEBHOOK_URL=(
  "ALERT_WEBHOOK_URL|ALERT_WEBHOOK_URL|Slack/Discord incoming webhook URL (server-error-sink + uptime-monitor)"
)

# ── 6. CRON_SECRET ───────────────────────────────────────────────
# Bearer token guarding /api/cron/* routes (e.g. abandoned-checkouts,
# check-supabase-pitr). Auto-generated openssl rand -base64 32 when
# `$CRON_SECRET` shell var is unset AND --auto-generate is passed.
CATEGORY_CRON_SECRET=(
  "CRON_SECRET|CRON_SECRET|Bearer token for cron route auth; auto-generates with --auto-generate"
)

# ── 7. NEXT_PUBLIC_* (browser-exposed) ────────────────────────────
# env vars starting with NEXT_PUBLIC_ are bundled into the client
# JS at build time. They MUST be set in the Vercel project-wide env
# (not just Production scope) if Previews need them. NEXT_PUBLIC_APP_URL
# is the canonical public URL used in cron-emails + OAuth redirects.
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY is excluded — see NOT-in-scope
# above.
CATEGORY_NEXT_PUBLIC=(
  "NEXT_PUBLIC_APP_URL|APP_URL|Public app URL (e.g. https://www.courssy.com) — used in cron emails + OAuth redirects"
  "NEXT_PUBLIC_SUPABASE_URL|SUPABASE_URL|Same as SUPABASE_URL (browser-exposed; client-side Supabase init)"
  "NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_ANON_KEY|Supabase anon JWT (browser-safe; client-side Supabase init)"
)

# ── 8. Other optional (skipped silently if shell vars unset) ─────
# LOG_ERROR_SECRET — guard for /api/log-error endpoint (PM2-style
# central-log shipper). OPENAI_API_KEY — optional tier for translations
# (see docs/production.md §5.1). Both are skipped on unset shell var,
# matching env.ts' `optional: true` semantics. NB: WS_SECRET was
# REMOVED in cleanup C3 along with server.ts + src/lib/ws/* — the WS
# bridge is gone, so the secret has no consumer.
CATEGORY_OTHER_OPTIONAL=(
  "LOG_ERROR_SECRET|LOG_ERROR_SECRET|/api/log-error auth; auto-generates with --auto-generate"
  "OPENAI_API_KEY|OPENAI_API_KEY|OpenAI API key (optional tier — see docs/production.md §5.1)"
)

# ─── Add env vars by category ─────────────────────────────────────

ADDED=0
SKIPPED=0
FAILED=0

add_var() {
  local vercel_name="$1"
  local shell_var="$2"
  local description="$3"

  if _is_in_production "$vercel_name"; then
    printf '  [skip]    %-32s (already in Production)\n' "$vercel_name"
    SKIPPED=$((SKIPPED + 1))
    return 0
  fi

  local value="${!shell_var:-}"

  # Auto-generate the 2 random secrets if the flag is set
  if [[ -z "$value" && "$IS_AUTO_GENERATE" == true ]]; then
    case "$vercel_name" in
      CRON_SECRET|LOG_ERROR_SECRET)
        value="$(_gen_secret)"
        printf '  [gen]     %-32s (auto-generated %d-char secret)\n' "$vercel_name" "${#value}"
        ;;
    esac
  fi

  if [[ -z "$value" ]]; then
    printf '  [skip]    %-32s (shell var $%s is unset — pass --auto-generate for random secrets, otherwise export it)\n' "$vercel_name" "$shell_var"
    SKIPPED=$((SKIPPED + 1))
    return 0
  fi

  if [[ "$IS_DRY_RUN" == true ]]; then
    printf '  [dry-run] %-32s <- $%s (%s)\n' "$vercel_name" "$shell_var" "$description"
    SKIPPED=$((SKIPPED + 1))
    return 0
  fi

  printf '  [add]     %-32s <- $%s\n' "$vercel_name" "$shell_var"
  if printf '%s\n' "$value" | vercel env add "$vercel_name" production >/dev/null 2>&1; then
    ADDED=$((ADDED + 1))
  else
    local rc=$?
    printf '  [FAIL]    %-32s (vercel env add returned %d — check value format / Vercel plan limits)\n' "$vercel_name" "$rc" >&2
    FAILED=$((FAILED + 1))
    return 1
  fi
}

add_category() {
  local category_name="$1"
  shift
  local entries=("$@")
  printf '\n══ %s ══\n' "$category_name"
  for entry in "${entries[@]}"; do
    IFS='|' read -r vercel_name shell_var description <<< "$entry"
    add_var "$vercel_name" "$shell_var" "$description" || true
  done
}

add_category "1. Supabase DB + Auth"     "${CATEGORY_SUPABASE_DB_AUTH[@]}"
add_category "2. Lemon Squeezy"          "${CATEGORY_LEMONSQUEEZY[@]}"
add_category "3. Email (SMTP)"           "${CATEGORY_EMAIL_SMTP[@]}"
add_category "4. Redis (Upstash)"        "${CATEGORY_REDIS[@]}"
add_category "5. ALERT_WEBHOOK_URL"      "${CATEGORY_ALERT_WEBHOOK_URL[@]}"
add_category "6. CRON_SECRET"            "${CATEGORY_CRON_SECRET[@]}"
add_category "7. NEXT_PUBLIC_*"          "${CATEGORY_NEXT_PUBLIC[@]}"
add_category "8. Other optional"         "${CATEGORY_OTHER_OPTIONAL[@]}"

# ─── Final summary + diff ─────────────────────────────────────────

vercel env ls production 2>/dev/null | awk 'NR>1 && $1 != "" {print $1}' | sort -u > "$AFTER_FILE"

printf '\n══ Summary ══\n'
printf '  Categories walked:   8\n'
printf '  Already present:     %d (skipped — verified via vercel env ls)\n' "$SKIPPED"
printf '  Newly added:         %d\n' "$ADDED"
if [[ "$FAILED" -gt 0 ]]; then
  printf '  Failed:              %d\n' "$FAILED" >&2
fi

# Diff: which vars moved from "missing" → "present" this run?
printf '\n══ Diff (newly added this run) ══\n'
if [[ "$ADDED" -eq 0 ]]; then
  printf '  (none — script is idempotent; re-run after exporting missing shell vars)\n'
else
  comm -13 "$EXISTING_FILE" "$AFTER_FILE" | sed 's/^/  + /'
fi

printf '\n══ Verify ══\n'
printf '  npx vercel env ls production\n'
printf '\n── Future runs will skip these vars (idempotent). ──\n'

if [[ "$FAILED" -gt 0 ]]; then
  printf '\n⚠️  %d env var(s) failed to add. Re-run this script after fixing them:\n' "$FAILED" >&2
  printf '   - The script will skip vars already added.\n' >&2
  printf '   - Common fixes: value with shell-special chars (quote on export),\n' >&2
  printf '     Vercel plan env-var limits, value-too-long.\n' >&2
  exit 3
fi

if [[ "$IS_DRY_RUN" == true ]]; then
  printf '\n✅ Dry-run complete. Re-run without --dry-run to apply.\n'
elif [[ "$ADDED" -gt 0 ]]; then
  printf '\n✅ vercel-prod-env complete. %d new env var(s) added, %d skipped.\n' "$ADDED" "$SKIPPED"
else
  printf '\n✅ vercel-prod-env complete. All Production env vars already present (idempotent).\n'
fi
