/** Reviewed eslint-disable inventory. Position is part of the review contract. */
export const ESLINT_DISABLE_ALLOWLIST = [
  ["src/app/(locale)/[locale]/[domain]/(member)/community/page.tsx", "react-hooks/purity", 158],
  ["src/app/admin/orders/page.tsx", "react-hooks/set-state-in-effect", 63],
  ["src/app/admin/products/[id]/page.tsx", "react-hooks/set-state-in-effect", 130],
  ["src/app/admin/products/[id]/page.tsx", "react-hooks/exhaustive-deps", 131],
  ["src/app/admin/products/[id]/page.tsx", "react-hooks/set-state-in-effect", 143],
  ["src/app/admin/products/page.tsx", "react-hooks/set-state-in-effect", 15],
  ["src/app/admin/users/page.tsx", "react-hooks/set-state-in-effect", 66],
  ["src/app/u/[username]/page.tsx", "react-hooks/purity", 149],
  ["src/components/admin/lesson-builder.tsx", "react-hooks/set-state-in-effect", 24],
  ["src/components/auth/auth-form.tsx", "react-hooks/set-state-in-effect", 54],
  ["src/components/auth/auth-form.tsx", "react-hooks/exhaustive-deps", 67],
  ["src/components/chat/chat-view.tsx", "react-hooks/set-state-in-effect", 223],
  ["src/components/course/lesson-notes.tsx", "react-hooks/set-state-in-effect", 49],
  ["src/components/course/lesson-progress-button.tsx", "react-hooks/set-state-in-effect", 50],
  ["src/components/course/premium-video-player.tsx", "react-hooks/set-state-in-effect", 60],
  ["src/components/course/video-paywall.tsx", "react-hooks/set-state-in-effect", 82],
  ["src/components/creator/SidebarTree.test.tsx", "@typescript-eslint/triple-slash-reference", 33],
  ["src/components/ebook/ebook-reader.tsx", "react-hooks/set-state-in-effect", 74],
  ["src/components/ebook/ebook-reader.tsx", "react-hooks/immutability", 95],
  ["src/components/ebook/ebook-reader.tsx", "react-hooks/exhaustive-deps", 102],
  ["src/components/funnel/language-alert.tsx", "react-hooks/set-state-in-effect", 48],
  ["src/components/funnel/language-selector.tsx", "react-hooks/immutability", 378],
  ["src/components/funnel/language-selector.tsx", "react-hooks/immutability", 379],
  ["src/components/funnel/social-proof.tsx", "react-hooks/exhaustive-deps", 94],
  ["src/components/funnel/social-proof.tsx", "react-hooks/exhaustive-deps", 125],
  ["src/components/pwa-install-banner.tsx", "react-hooks/set-state-in-effect", 51],
  ["src/domains/creator-ops/read-models/prisma-content-repository.ts", "@typescript-eslint/no-explicit-any", 72],
  ["src/domains/creator-ops/read-models/prisma-content-repository.ts", "@typescript-eslint/no-explicit-any", 87],
  ["src/domains/creator-ops/read-models/prisma-content-repository.ts", "@typescript-eslint/no-explicit-any", 103],
  ["src/lib/blocks/BLOCK_REGISTRY.tsx", "@typescript-eslint/no-explicit-any", 76],
  ["src/lib/logging/use-log-error.ts", "react-hooks/exhaustive-deps", 72],
] as const;

export type EslintDisableAllowlistEntry = (typeof ESLINT_DISABLE_ALLOWLIST)[number];
